import { Command } from "commander";
import { createRequire } from "node:module";
import { runAdd } from "./commands/add.js";
import { runInit } from "./commands/init.js";
import { runList } from "./commands/list.js";
import { runUpdate } from "./commands/update.js";

const require = createRequire(import.meta.url);
const { version } = require("../package.json") as { version: string };

const program = new Command();

program
  .name("ngx-base-cli")
  .description(
    "CLI to scaffold BaseService, CacheService, and HTTP artifacts in Angular projects"
  )
  .version(version);

program
  .command("init")
  .description(
    "Generate base/cache services, models, and optional interceptors in the project"
  )
  .option("-c, --cwd <dir>", "Angular project directory", process.cwd())
  .option("-y, --yes", "Skip interactive prompts — select a preset instead")
  .action(async (opts: { cwd?: string; yes?: boolean }) => {
    await runInit(opts.cwd ?? process.cwd(), opts.yes ?? false);
  });

program
  .command("add")
  .description(
    "Generate a feature service extending BaseService under <outputDir>/services/"
  )
  .argument("<name>", "feature name (e.g. user, user-profile)")
  .option("-c, --cwd <dir>", "Angular project directory", process.cwd())
  .action(async (name: string, opts: { cwd?: string }) => {
    await runAdd(name, opts.cwd ?? process.cwd());
  });

program
  .command("update")
  .description(
    "Regenerate init-generated files from .ngx-base-cli.json (shows diff)"
  )
  .option("-c, --cwd <dir>", "Angular project directory", process.cwd())
  .option("-y, --yes", "Apply all updates without prompts")
  .action(async (opts: { cwd?: string; yes?: boolean }) => {
    await runUpdate(opts.cwd ?? process.cwd(), opts.yes ?? false);
  });

program
  .command("list")
  .description(
    "Show sync status of each file that would be generated by init (present/diverge/absent)"
  )
  .option("-c, --cwd <dir>", "Angular project directory", process.cwd())
  .action(async (opts: { cwd?: string }) => {
    await runList(opts.cwd ?? process.cwd());
  });

program.parse();
